### ISSUE TITLE
pregunta sobre request del lado del servidor

### ISSUE THREAD

**Issue by luisramra** [aamatte/Tutorial-Sync-Adapter#1]
Hola! estoy siguiendo tu tutorial para hacer la sincronización que estoy desarrollando y primero que nada agradecerte! es muy bueno tanto en contenido, temas y es muy claro! solo, llegué al final y no he logrado hacer los web services para hacer la comunicación del sync adapter con el servidor, o si supieras de algún tutorial o ejemplo que pueda seguir para lograrlo! gracias de antemano!

**Comment by aamatte** [comment]
Me alegro que te sea de utilidad!
¿El servicio web ya está desarrollado? Si no está desarrollado hay muchas alternativas para hacerlo. Puedes usar Rails 5 en modo API, o algo con Node/Express.js dependiendo del lenguaje que más te manejas. Para eso puedes buscar en Google, hay muchísimos tutoriales que te guiarán en lo básico. Si el servicio ya está desarrollado, tienes que consumir ese servicio desde la aplicación. Para eso te recomiendo las librerías [Volley](http://slides.com/dmytrodanylyk/volley/fullscreen#/) o [Retrofit](https://square.github.io/retrofit/). Hay muchos tutoriales sobre como usarlos buscando en Google. Espero que eso te ayude!

**Comment by luisramra** [comment]
muchas gracias por la respuesta, crees que podrías mostrarme como hiciste los web services del ejemplo para darme una idea? estoy leyendo los tutoriales de volley pero más información jamás afecta, de cualquier forma muchas gracias por tu tutorial y por la respuesta
